### ISSUE TITLE
A problem abount the adsh training

### ISSUE THREAD

**Issue by kfxw** [IIE-MR/DIHN#3]
Hi!

Thanks for your code. I have a question about some training details of adsh.py, I would be grateful if you can help me a little bit.

It seems that the performance of ADSH on cifar10 reported in your paper is a reimplemented result, right? If so, did you use the 'num_seen' option when you trained the ADSH model? And if you used this option in refactoring the ADSH, what was the setting of this option? Was it the default '7'?

And do you have any idea that why the ADSH's performance you report is much higher than that in ADSH's original Neurips paper?

Thanks!

**Comment by TreezzZ** [comment]
Hi！
In DIHN paper, the setting of baseline ADSH is same as ADSH orignal paper. But in this implement, num_seen is set to 7 because I misunderstood the baseline setting of DIHN at first :(. Orignal DIHN is implemented on MATLAB by Wu, and I reimplemented it on PyTorch and put it on github . 
> "And do you have any idea that why the ADSH's performance you report is much higher than that in ADSH's original Neurips paper?"

Actually, the mAP performance of ADSH in DIHN is similar to original ADSH paper(and ADSH is pubulished on 2018-AAAI, not NIPS.)

**Comment by kfxw** [comment]
Thx!
